name: MatchIn
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  cupertino_icons: ^1.0.8

  #--> functional programming
  dartz: ^0.10.1

  #--> http requests
  dio: ^5.11.1

  #--> equality comparison of objects
  equatable: ^2.1.0
  
  #--> Firebase services
  # firebase_core: ^4.14.0
  # firebase_messaging: ^16.6.0
  flutter:
    sdk: flutter

  #--> state management
  flutter_bloc: ^9.1.1

  #--> App icon
  flutter_launcher_icons: ^0.14.4

  #--> local Notifications
  
  # flutter_local_notifications: ^22.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3

  #--> responsive UI
  flutter_screenutil: ^5.9.3

  #--> secure storage
  flutter_secure_storage: ^11.1.0

  #--> SVG support
  flutter_svg: ^2.3.0

  #--> dependency injection (service locator)
  get_it: ^9.2.1

  #--> navigation and routing
  go_router: ^18.0.1

  #--> shared preferences storage
  shared_preferences: ^2.5.5
  file_picker: ^13.1.0

  #--> Navigation bar
  google_nav_bar: ^5.0.7

  #--> Lottie animations
  lottie: ^3.6.1

  #--> web view
  flutter_inappwebview: ^6.1.5

  #--> OTP animation fields
  otp_animated_fields: ^0.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #! =============== Assets ===============
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/animations/

  #! =============== Fonts ===============
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/dm_sans/DMSans_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/dm_sans/DMSans_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/dm_sans/DMSans_18pt-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
          weight: 700

    - family: Alexandria
      fonts:
        - asset: assets/fonts/alexandria/Alexandria-Regular.ttf
          weight: 400
        - asset: assets/fonts/alexandria/Alexandria-Medium.ttf
          weight: 500
        - asset: assets/fonts/alexandria/Alexandria-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/alexandria/Alexandria-Bold.ttf
          weight: 700

    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700

#! The following section is specific to Flutter Intl package
flutter_intl:
  enabled: true

  #! The following section is specific to assets generation
flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: null

